export const THEMES = {
  nightTender: {
    id: "nightTender",
    name: "最后的舞会",
    palette: {
      "--bg-primary": "#191970",
      "--bg-secondary": "#121244",
      "--text-primary": "#F7E7CE",
      "--text-muted": "#d7c6ac",
      "--accent-primary": "#FF00FF",
      "--accent-secondary": "#F7E7CE",
      "--border-color": "rgba(247, 231, 206, 0.8)",
      "--card-shadow": "0 12px 36px rgba(255, 0, 255, 0.18)",
      "--grain-opacity": "0.12",
      "--cursor-color": "#FF00FF",
      "--font-heading": "'Playfair Display', serif",
      "--font-body": "'Inter', 'Noto Sans SC', sans-serif",
      "--panel-radius": "18px",
    },
    animation: {
      page: { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.7 } },
      card: { whileHover: { y: -4, boxShadow: "0 14px 30px rgba(255,0,255,0.22)" } },
    },
    easterEgg: "在这个温柔的夜里，所有承诺都像香槟泡沫。",
  },
  aleph: {
    id: "aleph",
    name: "沙之书",
    palette: {
      "--bg-primary": "#000000",
      "--bg-secondary": "#0b0b0b",
      "--text-primary": "#FFFFFF",
      "--text-muted": "#d7d7d7",
      "--accent-primary": "#8a2be2",
      "--accent-secondary": "#00f5ff",
      "--border-color": "rgba(255, 255, 255, 0.7)",
      "--card-shadow": "0 12px 30px rgba(138, 43, 226, 0.35)",
      "--grain-opacity": "0.08",
      "--cursor-color": "#00f5ff",
      "--font-heading": "'Space Grotesk', 'Noto Sans SC', sans-serif",
      "--font-body": "'Inter', 'Noto Sans SC', sans-serif",
      "--panel-radius": "12px",
    },
    animation: {
      page: {
        initial: { opacity: 0, scale: 0.98, filter: "blur(6px)" },
        animate: { opacity: 1, scale: 1, filter: "blur(0px)" },
        transition: { duration: 0.6 },
      },
      card: { whileHover: { rotate: [0, -1.2, 1.2, 0], scale: 1.01 } },
    },
    easterEgg: "我在一个点里看见了世界所有的点。",
  },
  furySound: {
    id: "furySound",
    name: "康普生家的午后",
    palette: {
      "--bg-primary": "#808080",
      "--bg-secondary": "#6e6e6e",
      "--text-primary": "#1a1a1a",
      "--text-muted": "#2a2a2a",
      "--accent-primary": "#FFFF00",
      "--accent-secondary": "#8B0000",
      "--border-color": "#1a1a1a",
      "--card-shadow": "7px 7px 0 #8B0000",
      "--grain-opacity": "0.2",
      "--cursor-color": "#8B0000",
      "--font-heading": "'Anton', 'Noto Sans SC', sans-serif",
      "--font-body": "'Inter', 'Noto Sans SC', sans-serif",
      "--panel-radius": "255px 15px 225px 15px / 15px 225px 15px 255px",
    },
    animation: {
      page: { initial: { opacity: 0, x: -10 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.42 } },
      card: { whileHover: { x: 2, y: -2 } },
    },
    easterEgg: "时间不是直线，它是一叠被揉皱的纸。",
  },
  castle: {
    id: "castle",
    name: "土地测量员K",
    palette: {
      "--bg-primary": "#7F8C8D",
      "--bg-secondary": "#556b6b",
      "--text-primary": "#f4efe8",
      "--text-muted": "#d8d0c5",
      "--accent-primary": "#2F4F4F",
      "--accent-secondary": "#3E2723",
      "--border-color": "rgba(244, 239, 232, 0.35)",
      "--card-shadow": "0 14px 28px rgba(25, 20, 18, 0.45)",
      "--grain-opacity": "0.16",
      "--cursor-color": "#f4efe8",
      "--font-heading": "'Merriweather', 'Noto Serif SC', serif",
      "--font-body": "'Inter', 'Noto Sans SC', sans-serif",
      "--panel-radius": "16px",
    },
    animation: {
      page: { initial: { opacity: 0, y: 18 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.62 } },
      card: { whileHover: { backdropFilter: "blur(5px)", scale: 1.01 } },
    },
    easterEgg: "你越靠近城堡，雾就越浓。",
  },
  outsider: {
    id: "outsider",
    name: "默尔索的夏天",
    palette: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f8f8f8",
      "--text-primary": "#111111",
      "--text-muted": "#3d3d3d",
      "--accent-primary": "#FF4500",
      "--accent-secondary": "#32CD32",
      "--border-color": "#111111",
      "--card-shadow": "0 0 0 2px #111111, 8px 8px 0 #FF4500",
      "--grain-opacity": "0.1",
      "--cursor-color": "#32CD32",
      "--font-heading": "'Permanent Marker', 'Noto Sans SC', sans-serif",
      "--font-body": "'Inter', 'Noto Sans SC', sans-serif",
      "--panel-radius": "10px",
    },
    animation: {
      page: { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.5 } },
      card: { whileHover: { rotate: [0, -0.8, 0.6, 0], scale: 1.01 } },
    },
    easterEgg: "今天，妈妈死了。也可能是昨天，我不知道。",
  },
};

export const THEME_ORDER = ["nightTender", "aleph", "furySound", "castle", "outsider"];
